config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :posts
  root 'home#home'
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'
  get 'chatroom', to: 'chatroom#index'
  get 'me', to: 'profiles#me'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	# Each Message belongs to a user
	belongs_to :user

	# Require message content and user ID to be present
	validates :content, presence: true
	validates :user_id, presence: true, numericality: true

	# Once message has been saved, broadcast it
	after_create_commit :broadcast_message

	private

	def broadcast_message
		MessageBroadcastJob.perform_later(self)
	end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true

  validates :title, presence: true
  validates :content, presence: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, dependent: :destroy

  validates :user_id, presence: true, uniqueness: true, numericality: true
  validates :name, presence: true, length: { maximum: 40 }

  scope :profile_info, ->(user) {where(["user_id = ?", user.id])}
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  after_create :create_profile
  
  has_many :messages, dependent: :destroy
  has_many :posts, dependent: :destroy # Destroy Posts if user account is deleted
  has_one :profile, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true

  def create_profile
    Profile.create(:name => self.email.partition("@").first, :user => self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
	def index
		# Only get messages to nil, the global chatroom
		@messages = Message.where(to_id: nil).order(created_at: :desc)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def contact
  end

  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]
    
    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end

    redirect_to root_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:me]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /me
  def me
    # Get the first and only record from the scope
    @profile = Profile.profile_info(current_user).first
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :admin, :birthday, :student, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/chatroom/index.html.erb
<% if !signed_in? %>
	<div style="color:red; id="alert"><p><%= t(".signed_out_message") %></p></div>
<% end %>

<h1 class="title"><%= t(".title") %></h1>

<%= form_with url: '#', html: {id: 'msg_new'} do |f| %>
  <%= f.text_field :attr, placeholder: "Message", id: 'msg_content', :autocomplete => :off %>
  <%= f.submit "Send" %>
<% end %>

<div id="messages">
  <%= render @messages %>
</div>

app/views/home/contact.html.erb
<h1 class="title"><%= t(".title") %></h1>
<p><%= t(".contact_us") %></p>

<%= form_tag request_contact_path, method: 'post' do %>
	<%= label_tag 'name', t('.name') %>
	<%= text_field 'name', '', title: t('.enter_name'), size: 50 %>
	<%= label_tag :email, t('.email') %>
	<%= email_field_tag :email, '', title: t('.enter_email') %>
	<%= label_tag 'telephone', t('.telephone') %>
	<%= telephone_field_tag 'telephone', '', title: t('.enter_telephone') %>
	<%= label_tag :message, t('.message') %>
	<%= text_field_tag :message, '', title: t('.enter_message'), size: 100 %>
	<%= submit_tag t('.submit') %>
<% end %>

app/views/home/home.html.erb
<h1 class="title"><%= t("app_title") %></h1>
<p><%= t("app_description") %></p>
<div class="row d-flex align-items-center justify-content-center">
	<%= image_tag("client-server-model.jpg", class: "home-image") %><br/>
</div>
	<p class="home-description"><%= t(".reminder") %></p>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<% # My name doesn't change over langauges so it's the same %>
		<span class="text-muted">&copy; <a href="mailto:mr00846@surrey.ac.uk">Matthew Reid</a> <%= Time.current.year %> &mdash; <%= t("footer") %></span>
	</div>
</footer>

app/views/layouts/_header.html.erb
<div id="navigation">
	<nav class="navbar navbar-default header">
		<ul class="nav">
			<a class="navbar-brand" href="/"><%= t("app_title") %></a>
			<li class="nav-item">
				<a class="nav-link" href="/chatroom"><%= t("chatroom.index.title") %></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/posts"><%= t("posts.index.title") %></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/contact"><%= t("home.contact.title") %></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/profiles"><%= t("profiles.index.title") %></a>
			</li>
		</ul>
		<ul class="nav">
			<span class="navbar-text">
				<% if signed_in? %>
					<%= t("greetings") %>, <a href="/me"><%= current_user.email %></a>
				<% end %>
			</span>
			<li class="nav-item">
				<% if signed_in? %>
					<% # Signs out via DELETE request to '/sign_out' %>
					<%= button_to t("sign_out"), sign_out_path, method: :delete %>
				<% else %>
					<%= button_to t("sign_in"), sign_in_path, method: :get %>
				<% end %>
			</li>
		</ul>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("app_title") %></title>
    	<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		
		<script src="/assets/jquery.js" type="text/javascript"></script>

		<%= action_cable_meta_tag %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'modernizr' %>

		<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
  </head>

  <body>
		<%= render "layouts/header" %>
		
		<div class="content">
			<% flash.each do |key, value| %>
				<%= content_tag :div, content_tag(:p, value), style: "color:blue;font-weight:bold;", id: "#{key}" unless value.blank? %>
			<% end %>

			<%= yield %>
		</div>

		<%= render "layouts/footer" %>
  </body>
</html>

app/views/messages/_message.html.erb
<% profile = Profile.find_by(user: message.user) %>

<% if profile.present? %>
	<% if profile.admin %>
		<% userClass = "user-admin" %>
	<% elsif profile.student %>
		<% userClass = "user-student" %>
	<% else %>
		<% userClass = "user-standard" %>
	<% end %>

	<div class="message">
		<strong><a class="<%= userClass %>" href="/profiles/<%= profile.id %>"><%= profile.name %></a></strong>:
		<%= message.content %>
		<br>
		<small>at <%= l(message.created_at, format: :short) %></small>
	</div> 
<% end %>

app/views/posts/_form.html.erb
<% if !signed_in? %>
	<div style="color:red; id="alert"><p><%= t(".signed_out_message") %></p></div>
<% end %>
<div class="row">
  <div class="col-xs-3 col-md-7 post-form">
    <%= form_with(model: post, local: true) do |form| %>
      <% if post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, :autocomplete => :off  %>
      </div>

      <div class="field">
        <%= form.label :content %>
        <%= form.text_area :content, :autocomplete => :off, rows: "5"  %>
      </div>

      <% if signed_in? %>
        <%= form.hidden_field :user_id, value: current_user.id %>
      <% else%>
        <%= form.hidden_field :user_id, value: nil %>
      <% end %>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%
	def trimText(text, length)
		if text.length > length
			return text.first(length) + "..."
		else
			return text
		end
	end
%>

<h1 class="title"><%= t(".title") %></h1>

<table class="show-table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= trimText(post.title, 25) %></td>
        <td><%= trimText(post.content, 150) %></td>
        <td>
          <% if defined?(post.user.email) %>
            <%= post.user.email %>
          <% else %>
            Anonymous
          <% end %>
        </td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <% if defined?(@post.user.email) %>
  	<%= @post.user.email %>
  <% else %>
    Anonymous
  <% end %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <% # If the user is an admin, they can make others admins %>
  <% if signed_in? && Profile.find_by(user: current_user).admin %>
    <div class="field">
      <%= form.label :admin %>
      <%= form.check_box :admin %>
    </div>
  <% end%>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday, start_year: 1900, end_year: Time.current.year %>
  </div>

  <div class="field">
    <%= form.label :student %>
    <%= form.check_box :student %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<div style="color:red;" id="alert"><p><%= raw(t(".creation_info")) %></p></div>

<h1 class="title"><%= t(".title") %></h1>

<table class="show-table">
  <thead>
    <tr>
	    <th>ID</th>
      <th>Name</th>
      <th>Admin</th>
      <th>Birthday</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
	      <td><%= profile.user.id %></td>
        <td><%= profile.name %></td>
        <td><%= profile.admin ? 'Yes' : 'No' %></td>
        <td><%= profile.birthday || 'Unknown' %></td>
        <td><%= profile.student ? 'Yes' : 'No' %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Delete User', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/profiles/me.html.erb
<h1 class="title"><%= t(".your_details") %></h1>
<p><%= t(".assurance") %></p>
<% puts @profile %>
<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @profile.admin ? 'Yes' : 'No' %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @profile.birthday || "Unknown" %>
</p>

<p>
  <strong>Student:</strong>
  <%= @profile.student ? 'Yes' : 'No' %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.user.email %>
</p>

<p>
  <strong>Joined:</strong>
  <%= @profile.user.created_at %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @profile.admin ? 'Yes' : 'No' %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @profile.birthday %>
</p>

<p>
  <strong>Student:</strong>
  <%= @profile.student ? 'Yes' : 'No' %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.user.email %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>